sonata_admin:
    title: 'Urgencias Mecánicas'
    dashboard: 
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
    templates:
        layout: standard_layout.html.twig
sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
